### ISSUE TITLE
Check memory usage

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#552] opened 2021-12-29 08:15 UTC
Seems like monika's memory usage keeps increasing with time. Need to figure out to fix this.

**Comment by ilmiawan** [comment] 2022-01-11 08:09
the issue is occured when symon is down. it is due to monika still sending report to symon when the server is down, this in some way makes the memory loaded heavily.

1. need to stop getting probe after 3 times getProbes error
2. don't send any report after getProbes Error

**Comment by sapiderman** [comment] 2022-04-01 09:43
Seems the issue has been solved with optimizations from @ilmiawan 
closing this issue.

**Closed by sapiderman** 2022-04-01 09:43 UTC
Labels: bug
