### ISSUE TITLE
Not send report to Symon if monika-logs.db exists

### ISSUE THREAD

**Issue by kevin-hyperjump** [hyperjumptech/monika#593] opened 2022-01-31 08:10 UTC
Step to reproduce:

1. `rm -rf monika-logs.db`
2. Run Monika with Symon mode
3. Stop Monika and re-run with Symon mode

**Comment by nicnocquee** [comment] 2022-03-22 12:25
[This](https://u.pcloud.link/publink/show?code=XZhgC0VZbKxNM2jmO8QkPodFb3MHyzvR8CLV) is a monika-logs.db file that can replicate this issue.

**Comment by gsukanto** [comment] 2022-03-29 06:41
Closing this issue since the problem is happen in Symon (staging).
It's not related with Monika and has been fixed.

**Closed by gsukanto** 2022-03-29 06:41 UTC
Labels: bug
